### ISSUE TITLE
【Rexkentzheng】账号不对

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#325]
只能输入7位账号，但是宝宝的校园卡是12位的

---
**用户信息**
用户名：Rexkentzheng
手机型号：EVA-DL00（android - 360x532）
微信版本号：6.5.3
We重邮版本号：v0.1.2

**Comment by mcc108** [comment]
校园卡12位的吗？方便加We重邮用户反馈群487586022了解一下具体情况吗？
