### ISSUE TITLE
【刘浩】课表排版问题

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#338]
查看学期课表排版不好看

---
**用户信息**
用户名：刘浩（本科生-刘浩-2014211750）
手机型号：M3s（android - 360x570）
微信版本号：6.5.4
We重邮版本号：v0.1.2

![img](http://wecqupt.congm.in/Fhw0O8znJFNZTQpEv5Z-637A6ppg?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by xiaoliuhao** [comment]
我来试一下回复之后能不能看到
