### ISSUE TITLE
【uiots】一点小错误

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#342]
官网第一个多写了一个点

---
**用户信息**
用户名：uiots（本科生-王柯-2015211948）
手机型号：MX5（android - 360x570）
微信版本号：6.5.4
We重邮版本号：v0.1.2

![img](http://wecqupt.congm.in/FkJNzSOC6t3_Zn5LBeW00zI04Wxf?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by uiots** [comment]
这个是我提交的，不好意思没核实，主观臆断了

**Comment by mcc108** [comment]
@uiots 没事😁
