### ISSUE TITLE
【Overload】我的反馈记录无法显示次数

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#344]
我的反馈记录无法显示次数

---
**用户信息**
用户名：Overload（本科生-高小飞-2013211583）
手机型号：Redmi 4（android - 360x572）
微信版本号：6.5.4
We重邮版本号：v0.1.2

![img](http://wecqupt.congm.in/FnFZKYXlzSdqm_gOlgjxJrO3umjr?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by xiaoliuhao** [comment]
应该是之前没有反馈过,默认显示 "-"
