### ISSUE TITLE
【马列老太】未绑定

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#347]
账号密码都输入对了，也可以看到饭卡余额了。但课表打不开，显示未绑定。

---
**用户信息**
用户名：马列老太（教职工-杨雯-）
手机型号：R7005（android - 360x567）
微信版本号：6.5.4
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
感谢您的反馈,，目前此问题已经修复，期间给您带来的不便，请谅解。
