### ISSUE TITLE
【晓舸】课表未绑定

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#350]
如题，请问如何绑定？

---
**用户信息**
用户名：晓舸（教职工-黄晓舸-）
手机型号：iPhone 6<iPhone7,2>（ios - 375x603）
微信版本号：6.5.5
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
感谢您的反馈,，目前此问题已经修复，期间给您带来的不便，请谅解。
