### ISSUE TITLE
【大美不言】课表无法查询

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#352]
我的教务账号没有绑定成功，怎么办？

---
**用户信息**
用户名：大美不言（教职工-谭玉龙-）
手机型号：HM NOTE 1S（android - 360x567）
微信版本号：6.5.4
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
感谢您的反馈,，目前此问题已经修复，期间给您带来的不便，请谅解。
