### ISSUE TITLE
【嘀嘀嗒嗒】无法查课表

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#353]
无法查课表，显示没有绑定

---
**用户信息**
用户名：嘀嘀嗒嗒（教职工-田鑫-）
手机型号：iPhone 6<iPhone7,2>（ios - 375x603）
微信版本号：6.5.5
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
感谢您的反馈,，目前此问题已经修复，期间给您带来的不便，请谅解。
