### ISSUE TITLE
【一直都在】增加功能

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#357]
可以增加一个搜索功能呢，可以从中直接搜索图书馆中有没有自己需要的书

---
**用户信息**
用户名：一直都在（本科生-罗伟-2015210434）
手机型号：ZTE C880A（android - 360x567）
微信版本号：6.5.4
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
#368 增加搜书功能
