### ISSUE TITLE
【xuyj】查课表周次应该可以选择的

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#361]
如题。另外，课表学期应该也可以随时切换。还可以查上学期的课信息。

---
**用户信息**
用户名：xuyj（教职工-徐勇军-010516）
手机型号：HUAWEI TAG-AL00（android - 360x519）
微信版本号：6.5.4
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
老师您好, 课表的周次可以通过下方第几周左右的箭头进行切换的
查让学期的课程信息,我们会考虑以后加上这个功能
