### ISSUE TITLE
【小饼子】课表功能有缺陷

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#366]
课表没有跟周数走，本来第二周还是显示的第一周得课。严重bug

---
**用户信息**
用户名：小饼子（本科生-谭潇-2014214046）
手机型号：ivvi i3-01（android - 360x520）
微信版本号：6.5.4
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
#367
