### ISSUE TITLE
【ともえ】学生查询中班级查询无果

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#373]
查不到班级

---
**用户信息**
用户名：ともえ（本科生-陈梦圆-2015211827）
手机型号：MI MAX（android - 392.72726x630.1818）
微信版本号：6.5.4
We重邮版本号：v0.1.2

![img](http://wecqupt.congm.in/FrJ6f-o8JbIKZR69N_DanlfOxqO5?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by xiaoliuhao** [comment]
这个教务在线更新后就查不到班级了..

**Comment by xiaoliuhao** [comment]
今天乱写一通，终于可以查询班级了~
