### ISSUE TITLE
【李】教师课表无法查询

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#379]
上学期试用版还可以，这学期就不行了！

---
**用户信息**
用户名：李（教职工-李盘林-	040107）
手机型号：iPhone 6<iPhone7,2>（ios - 375x603）
微信版本号：6.5.5
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
建议您重新绑定一下 就可以查了
