### ISSUE TITLE
【半世轻浮#】课表显示下拉会左右抖动-有几率

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#381]
3台安卓手机都是酱紫。

---
**用户信息**
用户名：半世轻浮#（本科生-张文良-2014210314）
手机型号：ONE A2001（android - 360x568）
微信版本号：6.5.7
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
方便加一下反馈群详细描述一下吗? 487586022
