### ISSUE TITLE
【陪我看海呀！  好哇！】课表

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#382]
查询不到我的课表

---
**用户信息**
用户名：陪我看海呀！  好哇！（本科生-刘繁书-2016212356）
手机型号：OPPO R9tm（android - 360x574）
微信版本号：6.5.7
We重邮版本号：v0.1.2

![img](http://wecqupt.congm.in/FoxfYaCAKOKLpBIP-P84yaCuEKbg?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by xiaoliuhao** [comment]
已修复~
