### ISSUE TITLE
【青逼】查不到课表

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#383]
查不到课表

---
**用户信息**
用户名：青逼（本科生-叶玉壮-2016214056）
手机型号：SM-G9350（android - 411x659）
微信版本号：6.5.7
We重邮版本号：v0.1.2

![img](http://wecqupt.congm.in/FgUx-AH35srkg6W2uTxQkPT6Xtq7?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by xiaoliuhao** [comment]
已修复~
