### ISSUE TITLE
【喂，别跑】课表无法显示

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#384]
课表没法正常显示

---
**用户信息**
用户名：喂，别跑（本科生-杨永生-2016210620）
手机型号：CHM-TL00（android - 360x567）
微信版本号：6.5.7
We重邮版本号：v0.1.2

![img](http://wecqupt.congm.in/FhyVqZ23ew_pJj-oegZ114uwYVDE?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by xiaoliuhao** [comment]
已修复~
