### ISSUE TITLE
【liudm】首页显示问题

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#388]
好像是与一卡通的连接有问题。

---
**用户信息**
用户名：liudm（教职工-刘达明-030211）
手机型号：PLK-AL10（android - 0x0）
微信版本号：6.5.7
We重邮版本号：v0.1.2

![img](http://wecqupt.congm.in/FsD_9-PFHRZrzCCGqxQnG11VqnlE?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

![img](http://wecqupt.congm.in/FuOZkyqoMJ3_hIb5sRIB2MuCVaJs?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by xiaoliuhao** [comment]
恩 一卡通的数据库连不上了
