### ISSUE TITLE
【玲玲】全校学生成绩排名

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#393]
没有全校学生成绩排名

---
**用户信息**
用户名：玲玲（本科生-申梦玲-2016210212）
手机型号：vivo Y67（android - 360x568）
微信版本号：6.5.7
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
这个确实没有。。

**Comment by xiaoliuhao** [comment]
已更新，在成绩查询查询中左滑进入成绩总表，会有专业排名
