### ISSUE TITLE
【哈哈】考试安排和本人的不符

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#395]
如题

---
**用户信息**
用户名：哈哈（教职工-杜佳佳-	020803）
手机型号：iPhone 6s Plus<iPhone8,2>（ios - 414x672）
微信版本号：6.5.7
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
老师您好，我们在教务在线看到您的考试信息确实是这样的， 您是否方便提供下您查考试安排的渠道呢
