### ISSUE TITLE
【复活的鱼】建议把门课程学分附上

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#397]
可以编写一个程序来计算级点！

---
**用户信息**
用户名：复活的鱼（本科生-王聪-2016212806）
手机型号：iPhone 5s (GSM+CDMA)<iPhone6,2>（ios - 320x504）
微信版本号：6.5.7
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
新版本已添加~
