### ISSUE TITLE
【封叶】更新不及时

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#398]
自相矛盾，日期写的明天考试，提醒时间里写还有6天，数据基本一天一更新，不及时，太慢。在里面看校园消息步骤多，复杂，不方便

---
**用户信息**
用户名：封叶（本科生-宋贵林-2016214549）
手机型号：vivo Y31A（android - 360x569）
微信版本号：6.5.7
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
同学你好，感谢你对We重邮的反馈，数据更新问题目前我们正努力解决，那个校园消息指的是新闻资讯吗？还是说其他的一些功能
