### ISSUE TITLE
【代桓滔】课表数据错误

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#400]
java课 只有we重邮显示今天下午有课 教务在线小帮手都没课😑

---
**用户信息**
用户名：代桓滔（本科生-代桓滔-2015214044）
手机型号：iPhone 6s<iPhone8,1>（ios - 375x583）
微信版本号：6.5.8
We重邮版本号：v0.1.2

![img](http://wecqupt.congm.in/FnsQhOAvK-fcmcrt0rApxALDeppM?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

![img](http://wecqupt.congm.in/FjfO2M27aTbIO2rj0pJwz_FEl4AW?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

![img](http://wecqupt.congm.in/FhCwFu6JeX09VvHSZN78FBfKBNVQ?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by xiaoliuhao** [comment]
已修复
