### ISSUE TITLE
【Aqua】出现错误

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#401]
不能绑定，说我的密码或账号错误

---
**用户信息**
用户名：Aqua
手机型号：OPPO R7sm（android - 360x527）
微信版本号：6.5.8
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
账号密码是和一卡通认证平台一样的~ 忘记的话可以尝试找回密码后重新登录
