### ISSUE TITLE
【。。】帐号密码

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#405]
为什么我的帐号密码登不上，别人的都可以

---
**用户信息**
用户名：。。（本科生-杨飞-2015213840）
手机型号：PLK-TL01H（android - 360x532）
微信版本号：6.5.7
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
同学你好，We重邮的账号密码就是一卡通认证平台的账号密码，可以尝试一下~
