### ISSUE TITLE
【哈哈】进入教务在线，登入账号，查询考试安排

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#407]
进入教务在线，登入账号，查询考试安排。这些考试大部分都和我无关

---
**用户信息**
用户名：哈哈（教职工-杜佳佳-	020803）
手机型号：iPhone 6s Plus<iPhone8,2>（ios - 414x672）
微信版本号：6.5.9
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
老师您好，我们在教务在线查到的本学期确实是有这四门考试安排 
![image](https://user-images.githubusercontent.com/18715022/27672989-d911f9be-5cd0-11e7-9ad1-50e53141badd.png)
