### ISSUE TITLE
【周雪 Daisy】希望可以查和一卡通绑定的银行卡余额的信息。

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#408]
希望可以查和一卡通绑定的银行卡余额的信息。

---
**用户信息**
用户名：周雪 Daisy（本科生-周雪-2014210900）
手机型号：Redmi Note 4（android - 360x572）
微信版本号：6.5.8
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
这个银行卡的余额信息。。。还是用银行自带的APP把，估计银行是不会给我们开权限查的 = =
