### ISSUE TITLE
【Ss🙄】未录入研究生信息？

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#410]
如题

---
**用户信息**
用户名：Ss🙄（研究生-邵帅-S160231053）
手机型号：iPhone 6<iPhone7,2>（ios - 375x603）
微信版本号：6.5.7
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
非常抱歉.暂时还没有办法获取到研究生的信息
