### ISSUE TITLE
【mcuil】成绩查询模块

### ISSUE THREAD

**Issue by lanshan-admin** [mcc108/wecqupt#413]
成绩查询处没有信息，查询失败

---
**用户信息**
用户名：mcuil（本科生-刘昌猛-2014211600）
手机型号：PRA-AL00（android - 360x532）
微信版本号：6.5.10
We重邮版本号：v0.1.2

![img](http://wecqupt.congm.in/Fng_qAgHk5476b-q7UYrQp0ICSrG?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by xiaoliuhao** [comment]
同学你好，查成绩这块是需要教务在线登录密码的，由于你的登录密码不是默认的身份证后6位，所以无法替你查询成绩
