### ISSUE TITLE
学习&隐私建议

### ISSUE THREAD

**Issue by mohuishou** [mcc108/wecqupt#420]
最近正在写我们学校的小程序，we重邮目前做的很棒了，点个赞
反馈直接放到github issue这个方式很赞，但是github是开源，你们的issue里面包含太多的个人信息，学号姓名手机，本科，手机型号都出来了
建议去除一些

**Comment by xiaoliuhao** [comment]
嗯，感谢建议，这两天有空把个人信息部分去掉。（一开始是为了方便定位问题 = =  ，确实没考虑这么多）

**Comment by xiaoliuhao** [comment]
done
