### ISSUE TITLE
测试账号是否可以申请？？

### ISSUE THREAD

**Issue by CrismusLiu** [mcc108/wecqupt#426]
看了贵校的小程序，感觉做的很好，特此来学习下，无奈没有账号，特此一问。
如果没有测试账号，可否提供一些静态数据，这样可以看到小程序页面，在此谢过！！

**Comment by xiaoliuhao** [comment]
实在是抱歉，由于登录部分直接接入了学校的认证系统，所以暂时没有测试账号，如果需要更多页面可以参考这个链接：https://github.com/mcc108/wecqupt/issues/196 ， 想登录体验一下的话，欢迎加入我们的反馈群：487586022，我这边可以提供个人的账号给你。

**Comment by CrismusLiu** [comment]
您好，QQ群加不进去，可否发下您的个人账号，十分感谢。
